### ISSUE TITLE
[feature] Support docker / docker-compose secrets for steamKey

### ISSUE THREAD

**Issue by damianb** [screepers/screeps-launcher#13]
I'm a big fan of isolating secrets away from configuration.  Making secrets available in `docker-compose` (without running docker in swarm mode) is fairly easy, and supporting that feature should be straightforward enough.

Proposal: If `steamKeyFile` is specified instead of `steamKey`, then the exact contents of the file specified in `steamKeyFile` should be used.

To use this in docker-compose afterwards, the compose file would need to specify a new secret like so:

``` yaml
version: '3'
services:
  screeps:
    image: screepers/screeps-launcher
    volumes:
      - ./config.yml:/screeps/config.yml
      - screeps-data:/screeps
    ports:
      - 21025:21025/tcp
    environment:
      MONGO_HOST: mongo
      REDIS_HOST: redis
    restart: unless-stopped
    secrets:
      - screeps_steam_key

  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  redis:
    image: redis
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  redis-data:
  mongo-data:
  screeps-data:


secrets:
  screeps_steam_key:
    file: ./screeps_steam_key

```

Pros:

* configuration can be safely version controlled afterwards without recording secrets
* configuration can be more easily shared, since redaction should be less likely to be necessary

Cons:

* configuration logic will become more complex, since now either `steamKey` or `steamKeyFile` should be specified (exclusive or)

--- 

Unfortunately, I'm not familiar enough with Go, otherwise I'd throw a PR down instead of an issue.
