### ISSUE TITLE
modify config.sample.yml

### ISSUE THREAD

**Issue by TimMullett** [screepers/screeps-launcher#16]
Hi ags,

As seen on slack: I was trying to use the screeps-launcher\docker-compose instructions to install and run the private server, but was getting a bunch of errors related to the server not connecting to mongo/redis.

After a looking through the docker docs I modified config.yml:

```
env:
  shared:
    MONGO_HOST: localhost
    REDIS_HOST: localhost
```

to

```
env:
  shared:
    MONGO_HOST: mongo
    REDIS_HOST: redis
```

and this solved the problem.
Net result being that the only config required was renaming the file and adding my steam key.

I tried to create a PR but don't have permission, so adding an issue.

Thanks

Tim(Sca1ey)
