### ISSUE TITLE
Set server password 

### ISSUE THREAD

**Issue by AlexPlayin** [screepers/screeps-launcher#22]
Hi,

is there currently a way to set the password of the private server ? I have found no option for that in the examples nor in the config loading code.

Thanks :)

**Comment by ags131** [comment]
Just set it in the ENV variables, although be aware the server password makes it harder to use any API tools
```yaml
# config.yml
env:
  backend:
    SERVER_PASSWORD: password
```
